package po

import (
	"gorm.io/gorm"
	"time"
)

// Model is the base struct for all database tables, containing common fields
type Model struct {
	// Id Database primary key,a 64-bit unique ID generated by Snowflake algorithm
	Id int `gorm:"primaryKey;type:bigint(20) unsigned not null;autoIncrement:false;comment:Snowflake generated unique ID"`

	// CreatedAt record creation time
	CreatedAt time.Time `gorm:"type:datetime not null;index;default:CURRENT_TIMESTAMP;comment: Record creation time"`

	// UpdatedAt record update time
	UpdatedAt time.Time `gorm:"type:datetime not null;index;default:CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;comment: Last update time"`

	// DeletedAt record deletion time (soft delete)
	DeletedAt gorm.DeletedAt `gorm:"type:datetime;index;comment:Logical deletion marker (soft delete)"`
}
